services:

  Markocupic\ImportFromCsvBundle\Import\ImportFromCsv:
    arguments:
      - '@contao.framework'
      - '@session'
      - '@security.encoder_factory'
      - '%kernel.project_dir%'
    public: true

  Markocupic\ImportFromCsvBundle\Cron\Cron:
    arguments:
      - '@contao.framework'
      - '@Markocupic\ImportFromCsvBundle\Import\ImportFromCsv'
    public: true

  Markocupic\ImportFromCsvBundle\TlDca\TlImportFromCsv:
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@session'
      - '@translator'
      - '@twig'
      - '@Markocupic\ImportFromCsvBundle\Import\ImportFromCsv'
      - '%kernel.project_dir%'
    public: true