services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $projectDir: '%kernel.project_dir%'
      $csrfTokenName: '%contao.csrf_token_name%'
      $perRequest: '%markocupic_import_from_csv.max_inserts_per_request%'

  _instanceof:
    Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
      calls:
        - [ setContainer, [ '@service_container' ] ]

  Markocupic\ImportFromCsvBundle\:
    resource: ../../
    exclude: ../../{DependencyInjection,Resources}

  # Add a session bag
  Markocupic\ImportFromCsvBundle\Session\Attribute\ArrayAttributeBag:
    arguments:
      - _markocupic_import_from_csv_attributes
    calls:
      - [setName, [markocupic_import_from_csv]]
